### ISSUE TITLE
Security vulnerability in API wrapper

### ISSUE THREAD

**Issue by sharathkumaranbu** [topcoder-platform/topcoder-submission-api-wrapper#11]
Please update the lodash version in Submission API wrapper to get rid of security vulnerabilities which is getting propagated to all client application which uses this wrapper.

![image](https://user-images.githubusercontent.com/7723558/70252237-16570380-17a7-11ea-9da1-d380ee26f38d.png)

cc @callmekatootie @cwdcwd

**Comment by callmekatootie** [comment]
The vulnerability is most likely coming from `tc-core-library-js` - https://github.com/appirio-tech/tc-core-library-js/issues/23

**Comment by sharathkumaranbu** [comment]
Yes. I have added it in the both places. May be we need to update the version of tc-core-library-js if a new version is released.

**Comment by sharathkumaranbu** [comment]
We can use this tag https://github.com/appirio-tech/tc-core-library-js/tree/v2.6.4 now to resolve the vulnerability issue.
