### ISSUE TITLE
Invalid submission type

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/topcoder-submission-api-wrapper#2]
Currently, the docs, test data & tests are using/showing `ContestSubmission` as the submission `type`.

As per [this](https://github.com/topcoder-platform/tc-online-review/blob/e5381b5a7e8a2f6a8180742c072d2d94f6aa47aa/src/java/main/com/cronos/onlinereview/Constants.java#L1166), it should be `Contest Submission`

**Comment by callmekatootie** [comment]
Fixed in `develop`
